### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by emanuele-virgillito** [CodigoCristo/sublimepatch#1]
running on ubuntu 20.04 gives:
./run_sudo_linux.bin: 8: Syntax error: newline unexpected
any idea?

**Comment by CodigoCristo** [comment]
For Linux

sudo ./run_sudo_linux.bin

https://youtu.be/8gd6A-5e9Ik

**Comment by CodigoCristo** [comment]
sudo chmod +x run_sudo_linux.bin

sudo ./run_sudo_linux.bin

**Comment by emanuele-virgillito** [comment]
already gave execution permission but still the same error

**Comment by CodigoCristo** [comment]
And if you compile the source code

gcc main.c -o  run_sudo_linux

and then you run it

**Comment by CodigoCristo** [comment]
- Run in administrator mode Ubuntu

![image](https://user-images.githubusercontent.com/34531165/149259394-cba6e67d-dd67-4f96-95c5-dffc1f501d9c.png)

![image](https://user-images.githubusercontent.com/34531165/149259412-a587290f-7a42-4a7b-9464-7ccdbf4d72f3.png)

![image](https://user-images.githubusercontent.com/34531165/149259426-dc1c9753-52f6-40b7-a716-ffcd748a520a.png)

![image](https://user-images.githubusercontent.com/34531165/149259458-45ad173b-23fc-4685-baf7-0c4f5ed8150e.png)

![image](https://user-images.githubusercontent.com/34531165/149259475-b3f8c082-ac6c-47d0-847b-b2414446dd6e.png)

**Comment by emanuele-virgillito** [comment]
recompiled and solved, thank you
